// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWeeBDbLVHsvur1Ps1hvq-Hr8PVAW7xO8',
    appId: '1:295025535559:web:128dddba39b78d1d12df62',
    messagingSenderId: '295025535559',
    projectId: 'e-estates-267a4',
    authDomain: 'e-estates-267a4.firebaseapp.com',
    storageBucket: 'e-estates-267a4.appspot.com',
    measurementId: 'G-4SV2RN8CDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6qpNROowtt-R-b3twW7n5BtlEV1fKdtY',
    appId: '1:295025535559:android:e26d326606efa5ca12df62',
    messagingSenderId: '295025535559',
    projectId: 'e-estates-267a4',
    storageBucket: 'e-estates-267a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw2eUdqjdzlAPy7OF6Q5mNrOgBMuSb0UA',
    appId: '1:295025535559:ios:1dbd42ecea364ae512df62',
    messagingSenderId: '295025535559',
    projectId: 'e-estates-267a4',
    storageBucket: 'e-estates-267a4.appspot.com',
    iosBundleId: 'com.example.eEstates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw2eUdqjdzlAPy7OF6Q5mNrOgBMuSb0UA',
    appId: '1:295025535559:ios:679bae0a387e32a612df62',
    messagingSenderId: '295025535559',
    projectId: 'e-estates-267a4',
    storageBucket: 'e-estates-267a4.appspot.com',
    iosBundleId: 'com.example.eEstates.RunnerTests',
  );
}
